language: php
php:
  - 5.5
  - 5.4
install:
  - mysql -e 'CREATE DATABASE dingbat;'
  - mysql dingbat < setup/install.sql
  - cp config.sample.php config.php
  - sed -i 's/root/travis/g' config.php
  - sed -i 's/bitnami//g' config.php
  - sed -i 's/false/true/g' config.php
  - sed -i 's/root/travis/g' codeception.yml
  - sed -i 's/bitnami//g' codeception.yml
  - sed -i 's/\/Dingbat//g' tests/functional.suite.yml
  - php -S localhost:8080 &
  - composer install --dev
script:
  - php vendor/bin/codecept run functional --debug