language: php
php:
  - 7.0
install:
  - cp config.sample.php config.php
  - sed -i 's/root/travis/g' config.php
  - sed -i 's/secret//g' config.php
  - sed -i 's/false/true/g' config.php
  - sed -i 's/root/travis/g' codeception.yml
  - sed -i "s/'password'//g" codeception.yml
  - composer install --dev
  - mysql -e 'CREATE DATABASE machdas;'
  - php vendor/bin/phinx migrate -e dev
  - php vendor/bin/codecept build
  - php -S localhost:9000 -t ./public &
  - npm install
script:
  - node_modules/.bin/eslint frontend/
  - php vendor/bin/phpcs --standard=PSR2 backend/ public/api/index.php
  - php vendor/bin/codecept run --debug
